// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFtAUMEGElGDgxgFJI9DnW5iNImo_y4ro',
    appId: '1:63579187504:web:94d65eaf0ae3af109bc0f5',
    messagingSenderId: '63579187504',
    projectId: 'fogguard-e083',
    authDomain: 'fogguard-e083.firebaseapp.com',
    storageBucket: 'fogguard-e083.firebasestorage.app',
    measurementId: 'G-9QP3MCDMMR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGqGcQ92TQDjgjwx1WUuuiwtwtHT4rOpw',
    appId: '1:63579187504:android:71c3d275c93d7b619bc0f5',
    messagingSenderId: '63579187504',
    projectId: 'fogguard-e083',
    storageBucket: 'fogguard-e083.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1G9fXoKZycFF7BSxu0MMW_bpF7ZJT7Sw',
    appId: '1:63579187504:ios:47cbd770a8629d9e9bc0f5',
    messagingSenderId: '63579187504',
    projectId: 'fogguard-e083',
    storageBucket: 'fogguard-e083.firebasestorage.app',
    iosBundleId: 'com.example.fogguardApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1G9fXoKZycFF7BSxu0MMW_bpF7ZJT7Sw',
    appId: '1:63579187504:ios:47cbd770a8629d9e9bc0f5',
    messagingSenderId: '63579187504',
    projectId: 'fogguard-e083',
    storageBucket: 'fogguard-e083.firebasestorage.app',
    iosBundleId: 'com.example.fogguardApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFtAUMEGElGDgxgFJI9DnW5iNImo_y4ro',
    appId: '1:63579187504:web:09ec52af77cf49ab9bc0f5',
    messagingSenderId: '63579187504',
    projectId: 'fogguard-e083',
    authDomain: 'fogguard-e083.firebaseapp.com',
    storageBucket: 'fogguard-e083.firebasestorage.app',
    measurementId: 'G-J67C9T5Y4C',
  );
}
